import {
  Badge,
  Box,
  Container,
  Flex,
  HStack,
  Stack,
  Text,
} from '@chakra-ui/layout';
import Head from 'next/head';
import { Button, Grid, Link, Image } from '@chakra-ui/react';
import {
  AiFillInstagram,
  AiFillYoutube,
  AiOutlineTwitter,
} from 'react-icons/ai';
import { GrMail } from 'react-icons/gr';
import React from 'react';
import { GetStaticProps } from 'next';
import { request } from 'graphql-request';
import { homePageQuery } from '../graphql/queries/home';
import { HomePageQuery } from '../generated';
import NextImage from 'next/image';
import { SpecialGridItem } from '../components/SpecialGridItem';
import { BlogCard } from '../components/BlogCard';

export const getStaticProps: GetStaticProps = async (context) => {
  const landingPageData: HomePageQuery = await request(
    'http://localhost:4000/graphql',
    homePageQuery
  );
  return {
    props: landingPageData,
  };
};

export default function Home(props: HomePageQuery) {
  console.log(props.homepage.about['email']);
  return (
    <Box overflow='hidden'>
      <Head>
        <title>{props.homepage.hero.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container maxW='container.xl'>
        <main>
          <Box
            mt='5'
            pl='28'
            rounded='lg'
            position='relative'
            height='90vh'
            background='gray.300'
          >
            <HStack
              textColor='gray.600'
              spacing={{ base: '2', sm: '5' }}
              pr='4'
              pt='2'
              justifyContent='end'
            >
              {props.homepage.hero?.navlinks.split(',').map((nav) => {
                return (
                  <Link
                    key={nav}
                    href={
                      nav === 'contact'
                        ? `mailto:${props.homepage.contact.email}`
                        : '#'
                    }
                  >
                    <Text>{nav}</Text>
                  </Link>
                );
              })}
            </HStack>

            <Box
              mt={{ base: '10', md: '48', lg: '28', xl: '20' }}
              ml={{ base: '-20', md: '0.5' }}
            >
              <Text
                as='h1'
                fontSize={{
                  base: '2xl',
                  sm: '3xl',
                  md: '4xl',
                  lg: '5xl',
                  xl: '6xl',
                }}
                lineHeight='shorter'
                w={{ base: 'auto', sm: 'xs', md: 'sm', lg: 'md', xl: 'lg' }}
              >
                {props.homepage.hero.title}
              </Text>
            </Box>
            <Box alignSelf='flex-end'>
              <Image
                alt={props.homepage.hero.profile[0].name}
                src={props.homepage.hero.profile[0].url}
                position='absolute'
                bottom='0'
                borderBottomRightRadius='2xl'
                right='0'
                boxSize={{ base: '400', lg: '500' }}
                mt='16'
                objectFit='cover'
                alignSelf='flex-end'
                justifySelf='self-end'
              />
            </Box>
          </Box>
        </main>

        {/* About section */}
        <section>
          <Box
            mt='5'
            pl={{ base: '4', md: '28' }}
            rounded='lg'
            position='relative'
            background='blue.300'
          >
            <Grid
              templateColumns={{ base: 'repeat(1,1fr)', md: 'repeat(2,1fr)' }}
              templateRows={{ base: 'repeat(4,1fr)', md: 'repeat(2,1fr)' }}
              gap='7'
            >
              <SpecialGridItem
                title='Work.'
                description={props.homepage.about.work}
              />
              <SpecialGridItem
                title='Blogs.'
                description={props.homepage.about.blogs}
              />

              <Box p='3' mt={{ base: '0', md: '14' }}>
                <Link
                  href={`mailto:${props.homepage.contact.email}`}
                  display='inline'
                  color='green.800'
                  textDecoration='underline'
                  mr='2'
                >
                  Email me
                </Link>
                <Text color='gray.700' display='inline'>
                  {props.homepage.about.email}
                </Text>
              </Box>

              <SpecialGridItem
                title='Watch.'
                description={props.homepage.about.watch}
              >
                <Link
                  display='inline'
                  ml='2'
                  target='_blank'
                  href={props.homepage.contact.youtube}
                >
                  Watch on youtube.
                </Link>
              </SpecialGridItem>
            </Grid>
          </Box>
        </section>
      </Container>

      {/* work section */}
      <section>
        {props.homepage.projects.map((proj) => {
          return (
            <Box
              key={proj.title}
              backgroundImage={`url(${proj.bg.url})`}
              mt='10'
            >
              <Box
                maxW='xl'
                px={{ base: '10', md: '32' }}
                pt={{ base: '10', md: '32' }}
                color='whiteAlpha.800'
              >
                <Text as='h3' fontSize='4xl'>
                  {proj.title}
                </Text>
                <Text>
                  {proj.description}
                  <Link ml='4' color='blue.400' href={proj.url} target='_blank'>
                    {proj.url}
                  </Link>
                </Text>
                <Stack direction='row' mt='3'>
                  {proj.tools.split(',').map((tool) => (
                    <Badge key={tool}>{tool}</Badge>
                  ))}
                </Stack>
              </Box>

              <Box display='flex' justifyContent='end' p='4'>
                <Image src={proj.image.url} alt={proj.image.name} />
              </Box>
            </Box>
          );
        })}
      </section>

      {/* blog section */}

      <section>
        <Box>
          <Box backgroundColor='pink.300' px='5' pb='4'>
            <Flex flexWrap='wrap' justifyContent='center'>
              {props.posts.map((post) => (
                <BlogCard
                  key={post.title}
                  description={post.description}
                  title={post.title}
                  topics={[...post.topics.split(',')]}
                />
              ))}
            </Flex>

            <Box display='flex' justifyContent='end' my='4'>
              <Button>More posts</Button>
            </Box>
          </Box>
        </Box>
      </section>

      {/* social media section */}
      <section>
        <Box display='flex' flexDirection='column' alignItems='center' my='20'>
          <Text fontSize='6xl'>{props.homepage.contact.title}</Text>
          <HStack spacing='10'>
            <Link
              href={`mailto:${props.homepage.contact.email}`}
              target='_blank'
            >
              <GrMail size={30} />
            </Link>

            <Link href={props.homepage.contact.insta} target='_blank'>
              <AiFillInstagram size={30} />
            </Link>

            <Link href={props.homepage.contact.youtube} target='_blank'>
              <AiFillYoutube size={30} />
            </Link>

            <Link href={props.homepage.contact.twitter} target='_blank'>
              <AiOutlineTwitter size={30} />
            </Link>
          </HStack>
        </Box>
      </section>

      <section>
        <Box mx={5} display='flex' justifyContent='center' my='10'>
          <Text>
            Images by
            <Link
              href='https://unsplash.com/@marekpiwnicki'
              target='_blank'
              mx='2'
            >
              Marek Piwnicki &
            </Link>
            <Link href='https://www.pexels.com/@pixabay' target='_blank'>
              Pixabay
            </Link>
          </Text>
        </Box>
      </section>
    </Box>
  );
}
