import { Box, Container, Flex, HStack, Text } from '@chakra-ui/layout';
import Head from 'next/head';
import { Image, Link } from '@chakra-ui/react';
// import Link from 'next/link';

export default function Home() {
  return (
    <Box overflow='hidden'>
      <Head>
        <title>Welcome to My Portfolio and Blog Site</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container maxW='container.xl'>
        <Box
          mt='5'
          pl='28'
          rounded='lg'
          position='relative'
          height='90vh'
          background='gray.300'
        >
          <HStack
            textColor='gray.600'
            spacing={{ base: '5' }}
            pr='4'
            pt='2'
            justifyContent='end'
          >
            <Link href='#'>
              <Text>about</Text>
            </Link>
            <Link href='#'>
              <Text>contact</Text>
            </Link>

            <Link href='#'>
              <Text>blog</Text>
            </Link>

            <Link href='#'>
              <Text>work</Text>
            </Link>
          </HStack>

          <Box mt={{ base: '52', md: '48', lg: '28', xl: '20' }}>
            <Text
              as='h1'
              fontSize={{ base: '3xl', md: '4xl', lg: '5xl', xl: '6xl' }}
              lineHeight='shorter'
              ml={{ base: '-20', small: '-20' }}
              w={{ base: 'xs', md: 'sm', lg: 'md', xl: 'lg' }}
            >
              I am full stack web developer building web and mobile apps for
              businesses
            </Text>
          </Box>
          <Image
            src='/bg.png'
            position='absolute'
            bottom='0'
            right='0'
            boxSize={{ base: '400', md: '400', lg: '500', xl: '500' }}
            mt='16'
            objectFit='cover'
            alignSelf='flex-end'
            justifySelf='self-end'
          />
        </Box>
      </Container>
    </Box>
  );
}
